---
- name: cho-vm-1 - HTTPS only (443)
  hosts: cho-vm-1
  become: yes
  tasks:
    - name: Reset ufw
      ufw:
        state: reset
    - name: Deny all incoming
      ufw:
        policy: deny
        direction: incoming
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: 443
        proto: tcp
    - name: Enable ufw
      ufw:
        state: enabled
