---
- name: cho0vm-2 - SSH only (22)
  hosts: cho0vm-2
  become: yes
  tasks:
    - name: Reset ufw
      ufw:
        state: reset
    - name: Deny all incoming
      ufw:
        policy: deny
        direction: incoming
    - name: Allow SSH
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Enable ufw
      ufw:
        state: enabled
