---
- name: cho-vm-3 - Block all
  hosts: cho-vm-3
  become: yes
  tasks:
    - name: Reset ufw
      ufw:
        state: reset
    - name: Deny all incoming
      ufw:
        policy: deny
        direction: incoming
    - name: Enable ufw
      ufw:
        state: enabled
