---
- name: cho-vm-3 - Block all
  hosts: cho-vm-3
  become: yes
  tasks:
    - name: Install ufw
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Reset ufw
      command: ufw --force reset
      args:
        warn: false

    - name: Set default deny
      ufw:
        policy: deny
        direction: incoming

    - name: Enable ufw
      ufw:
        state: enabled
